version: '{build}'

# cache-bust 2016-05-20 11:03

cache:
  - '%LOCALAPPDATA%\Microsoft\dotnet -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\project.json'

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/dotnet/cli/v1.0.0-preview2/scripts/obtain/dotnet-install.ps1
  - powershell -File dotnet-install.ps1
  - set PATH=%PATH%;%LOCALAPPDATA%\Microsoft\dotnet

before_build:
  - dotnet restore -v minimal
  - powershell -File replace-meta.ps1 %APPVEYOR_BUILD_NUMBER% %APPVEYOR_REPO_TAG_NAME%

build_script:
  - cmd /c "cd DevExtreme.AspNet.TagHelpers.Generator && dotnet run"
  - dotnet build DevExtreme.AspNet.TagHelpers

test_script:
  - dotnet test DevExtreme.AspNet.TagHelpers.Tests 

after_test:
  - dotnet pack DevExtreme.AspNet.TagHelpers --configuration=Release

artifacts:
  - path: DevExtreme.AspNet.TagHelpers\bin\Release\*.nupkg