version: '{build}'

cache:
  - '%ProgramFiles%\dotnet -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> appveyor.yml, **\project.json'

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/dotnet/cli/v1.0.0-rc2/scripts/obtain/install.ps1'))

before_build:
  - dotnet restore -v minimal
  - powershell -File replace-meta.ps1 %APPVEYOR_BUILD_NUMBER% %APPVEYOR_REPO_TAG_NAME%

build_script:
  - cmd /c "cd DevExtreme.AspNet.TagHelpers.Generator && dotnet run"
  - dotnet build DevExtreme.AspNet.TagHelpers

test_script:
  - dotnet test DevExtreme.AspNet.TagHelpers.Tests 

after_test:
  - dotnet pack DevExtreme.AspNet.TagHelpers --configuration=Release

artifacts:
  - path: DevExtreme.AspNet.TagHelpers\bin\Release\*.nupkg